### PR TITLE
removed mode from IDistribution Fixes #16

### LINKED ISSUE #16: Mode of LP3
We need to implement the mode of LP3/ cut out the not implemented exception

### PR DESCRIPTION
**Pull request by rnugent3**

### CODE REVIEW

File: StatisticsTests/Distributions/SerializationTests.cs [hunk 1]
```diff
@@ -87,19 +87,20 @@ public void SerializationRoundTrip_Uniform(double min, double max, int n)
...
-            Assert.Equal(max, d.Max);
-            Assert.Equal(max, d2.Max);
-            Assert.Equal(d.Mode, d2.Mode);
-            Assert.Equal(mostlikely, d.Mode);
-            Assert.Equal(mostlikely, d2.Mode);
-            Assert.Equal(d.SampleSize, d2.SampleSize);
+            Triangular distributionTriangular = new Triangular(min, mostlikely,max ,n);
+            XElement element = distributionTriangular.ToXML();
+            IDistribution distribution = IDistributionExtensions.FromXML(element);
+            Triangular distributionTriangular2 = distribution as Triangular;
```
Comment (HenryGeorgist) [inline StatisticsTests/Distributions/SerializationTests.cs:93]: great

**Review by HenryGeorgist — APPROVED** [review]

**Comment by HenryGeorgist** [comment]
honestly, much like that, all of the descriptive properties that are mostly implemented {get;set;} on idistribution could probably be removed like mode
